name: "Datadog Static Analysis"
description: "Run a Datadog Static Analysis in your Github Action workflows"
author: "Datadog"
inputs:
  dd_api_key:
    description: "Your Datadog API key used to authenticate requests."
    required: true
    default: ""
  dd_app_key:
    description: "Your Datadog Application key used to authenticate requests."
    required: true
    default: ""
  dd_service:
    description: "The service you want your results tagged with."
    required: true
    default: ""
  dd_env:
    description: "The environment you want your results tagged with."
    required: false
    default: "none"
  dd_site:
    description: "The Datadog site. For example, users in the EU may want to set datadoghq.eu."
    required: false
    default: "datadoghq.com"
  cpu_count:
    description: "Set the number of CPUs used to by the analyzer."
    required: false
    default: "2"
  enable_performance_statistics:
    description: "Get the execution time statistics for analyzed files."
    required: false
    default: "false"
  debug:
    description: "Lets the analyzer print additional logs useful for debugging."
    required: false
    default: "no"
  subdirectory:
    description: "A subdirectory path to run an analysis from."
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    DD_API_KEY: ${{ inputs.dd_api_key }}
    DD_APP_KEY: ${{ inputs.dd_app_key }}
    DD_SERVICE: ${{ inputs.dd_service }}
    DD_ENV: ${{ inputs.dd_env }}
    DD_SITE: ${{ inputs.dd_site }}
    CPU_COUNT: ${{ inputs.cpu_count }}
    ENABLE_PERFORMANCE_STATISTICS: ${{ inputs.enable_performance_statistics }}
    ENABLE_DEBUG: ${{ inputs.debug }}
    SUBDIRECTORY: ${{ inputs.subdirectory }}
